# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_no',
            field=models.IntegerField(),
        ),
    ]
